nelmio_api_doc:
    documentation:
        info:
            title: Full-stack challenge
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!\_) # Accepts routes under / except /_*
